### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by gounthar** [rockchip-linux/ffmpeg#10]
I managed to configure and compile once your version of ffmpeg on a machine which has crashed since then.
I am now trying to get a consistent build on an OrangePi RK3399, but I sometimes fail to build, and other times, I just don't get the h264_rkmpp vcodec available.
What configure options should I use on the command line?
For the time being, I'm using:
```bash
 PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --arch=arm   --bindir="$HOME/bin"   --enable-rkmpp --disable-stripping  --enable-libaom   --enable-avisynth   --enable-avresample   --enable-chromaprint   --enable-frei0r  --enable-gpl   --enable-ladspa --enable-libass  --enable-libbs2b   --enable-libcaca   --enable-libcdio   --enable-libdc1394  --enable-libfdk-aac  --enable-libfontconfig   --enable-libfreetype   --enable-libfribidi   --enable-libgme   --enable-libgsm   --enable-libiec61883   --enable-libmp3lame --enable-libopenjpeg   --enable-libopenmpt   --enable-libopus   --enable-libpulse   --enable-librubberband   --enable-libshine   --enable-libsnappy   --enable-libsoxr   --enable-libspeex   --enable-libssh   --enable-libtheora   --enable-libtwolame   --enable-libvorbis   --enable-libvpx   --enable-libwavpack   --enable-libwebp   --enable-libx264   --enable-libx265   --enable-libxvid   --enable-libzmq   --enable-libzvbi   --enable-omx   --enable-openal   --enable-opengl   --enable-sdl2   --enable-shared   --incdir=/usr/include/arm-linux-gnueabihf   --libdir=/usr/lib/arm-linux-gnueabihf   --enable-nonfree --enable-rkmpp --enable-version3 --enable-libdrm  --extra-cflags="-I$HOME/ffmpeg_build/include"   --extra-ldflags="-L$HOME/ffmpeg_build/lib"   --extra-libs="-lpthread -lm -lnettle -lhogweed -lgmp"   --pkg-config-flags="--static"   --prefix="$HOME/ffmpeg_build"
```

Which branch should I use? Master? 4.0? 4.1?
Thanks.

**Comment by JeffyCN** [comment]
The key configs to enable rkmpp would be: "--enable-rkmpp --enable-libdrm --enable-version3"

There are multiple versions of ffmpeg we are using(due to legacy projects and patches)...

For new projects:
1/ we are using https://github.com/rockchip-linux/buildroot/tree/rockchip/2018.02-rc3/package/ffmpeg for buildroot
forked from rockchip/release/4.1 branch, and with more special chip hacks.

2/ i'm using a clean version(without legacy project patches, and no hardware encoding/zero-copy ffplay) on debian/ubuntu:
https://github.com/JeffyCN/FFmpeg/commits/4.1
